import { AxiosError } from 'axios';

export enum ErrorCode {
  NOT_FOUND_DATA = 'NOT_FOUND_DATA',
  DUPLICATE_DATA = 'DUPLICATE_DATA',
  INVALID_VALUE = 'INVALID_VALUE',
  UNMODIFIABLE_DATA = 'UNMODIFIABLE_DATA',
  FAIL_SEND_DATA = 'FAIL_SEND_DATA',
  FAIL_DATA_UPLOAD = 'FAIL_DATA_UPLOAD',
  FAIL_DATA_DOWNLOAD = 'FAIL_DATA_DOWNLOAD',
  FAIL_DATA_DELETE = 'FAIL_DATA_DELETE',
  FAIL_INTERNAL_CLIENT_API = 'FAIL_INTERNAL_CLIENT_API',
  UNAUTHORIZED = 'UNAUTHORIZED',
  NO_AUTHORITY = 'NO_AUTHORITY',
  JWT_SIGNATURE = 'JWT_SIGNATURE',
  JWT_MALFORMED = 'JWT_MALFORMED',
  JWT_EXPIRED = 'JWT_EXPIRED',
  JWT_UNSUPPORTED = 'JWT_UNSUPPORTED',
  JWT_ILLEGAL = 'JWT_ILLEGAL',
  JWT_NON_EXPIRED = 'JWT_NON_EXPIRED',
  JWT_MALFORMED_REFRESH_TOKEN = 'JWT_MALFORMED_REFRESH_TOKEN',
  JWT_EXPIRED_REFRESH_TOKEN = 'JWT_EXPIRED_REFRESH_TOKEN',
}

export interface CommonErrorResponse {
  error: ErrorCode;
  status: string;
  timestamp: string;
}

export type ErrorResponse = AxiosError<CommonErrorResponse>;
