/* tslint:disable */
/* eslint-disable */
/**
 * Mcafe V2 API
 * Mcafe V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 패배자 생성 rq
 * @export
 * @interface DashBoardRequestPost
 */
export interface DashBoardRequestPost {
  /**
   *
   * @type {number}
   * @memberof DashBoardRequestPost
   */
  looserSn: number;
  /**
   *
   * @type {string}
   * @memberof DashBoardRequestPost
   */
  gameType: DashBoardRequestPostGameTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum DashBoardRequestPostGameTypeEnum {
  PINBALL = 'PINBALL',
}
