/* tslint:disable */
/* eslint-disable */
/**
 * Mcafe V2 API
 * Mcafe V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 게임 준비 상태 업데이트 rq
 * @export
 * @interface GameReadyRequestPut
 */
export interface GameReadyRequestPut {
  /**
   *
   * @type {number}
   * @memberof GameReadyRequestPut
   */
  memberSn: number;
  /**
   *
   * @type {number}
   * @memberof GameReadyRequestPut
   */
  roomSn: number;
  /**
   *
   * @type {string}
   * @memberof GameReadyRequestPut
   */
  gameType: GameReadyRequestPutGameTypeEnum;
  /**
   *
   * @type {string}
   * @memberof GameReadyRequestPut
   */
  readyStatus: GameReadyRequestPutReadyStatusEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum GameReadyRequestPutGameTypeEnum {
  PINBALL = 'PINBALL',
}
/**
 * @export
 * @enum {string}
 */
export enum GameReadyRequestPutReadyStatusEnum {
  READY = 'READY',
  UNREADY = 'UNREADY',
}
