/* tslint:disable */
/* eslint-disable */
/**
 * Mcafe V2 API
 * Mcafe V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 로그인 유저 정보
 * @export
 * @interface MemberResponseLogin
 */
export interface MemberResponseLogin {
  /**
   *
   * @type {string}
   * @memberof MemberResponseLogin
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof MemberResponseLogin
   */
  phone: string;
  /**
   *
   * @type {string}
   * @memberof MemberResponseLogin
   */
  token: string;
}
