/* tslint:disable */
/* eslint-disable */
/**
 * Mcafe V2 API
 * Mcafe V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 회원 정보
 * @export
 * @interface MemberDto
 */
export interface MemberDto {
  /**
   *
   * @type {number}
   * @memberof MemberDto
   */
  memberSn: number;
  /**
   *
   * @type {string}
   * @memberof MemberDto
   */
  nickname: string;
}
