/* tslint:disable */
/* eslint-disable */
/**
 * Mcafe V2 API
 * Mcafe V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { MenuDto } from './menu-dto';

/**
 * 메뉴 리스트
 * @export
 * @interface MenuCategoryDto
 */
export interface MenuCategoryDto {
  /**
   *
   * @type {string}
   * @memberof MenuCategoryDto
   */
  name: string;
  /**
   *
   * @type {Array<MenuDto>}
   * @memberof MenuCategoryDto
   */
  menuList: Array<MenuDto>;
}
