/* tslint:disable */
/* eslint-disable */
/**
 * Mcafe V2 API
 * Mcafe V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { OptionDto } from './option-dto';

/**
 *
 * @export
 * @interface OptionGroupDto
 */
export interface OptionGroupDto {
  /**
   *
   * @type {string}
   * @memberof OptionGroupDto
   */
  name: string;
  /**
   *
   * @type {number}
   * @memberof OptionGroupDto
   */
  selectMin: number;
  /**
   *
   * @type {number}
   * @memberof OptionGroupDto
   */
  selectMax: number;
  /**
   *
   * @type {Array<OptionDto>}
   * @memberof OptionGroupDto
   */
  optionList: Array<OptionDto>;
}
