/* tslint:disable */
/* eslint-disable */
/**
 * Mcafe V2 API
 * Mcafe V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { MenuInfoDto } from './menu-info-dto';

/**
 * 주문 DTO
 * @export
 * @interface OrderDto
 */
export interface OrderDto {
  /**
   *
   * @type {number}
   * @memberof OrderDto
   */
  memberSn: number;
  /**
   *
   * @type {string}
   * @memberof OrderDto
   */
  memberNickname: string;
  /**
   *
   * @type {number}
   * @memberof OrderDto
   */
  roomSn: number;
  /**
   *
   * @type {MenuInfoDto}
   * @memberof OrderDto
   */
  menu: MenuInfoDto;
  /**
   *
   * @type {number}
   * @memberof OrderDto
   */
  quantity: number;
  /**
   *
   * @type {Array<number>}
   * @memberof OrderDto
   */
  optionList: Array<number>;
}
