/* tslint:disable */
/* eslint-disable */
/**
 * Mcafe V2 API
 * Mcafe V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 주문 생성 요청 객체
 * @export
 * @interface OrderRequestCreate
 */
export interface OrderRequestCreate {
  /**
   * 메뉴 코드
   * @type {string}
   * @memberof OrderRequestCreate
   */
  menuCode: string;
  /**
   * 방 sn
   * @type {number}
   * @memberof OrderRequestCreate
   */
  roomSn: number;
  /**
   * 옵션 목록
   * @type {Array<number>}
   * @memberof OrderRequestCreate
   */
  optionList: Array<number>;
}
