/* tslint:disable */
/* eslint-disable */
/**
 * Mcafe V2 API
 * Mcafe V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { MenuInfoDto } from './menu-info-dto';

/**
 * 메뉴 정보 요청 응답 객체
 * @export
 * @interface OrderGetMenuInfo
 */
export interface OrderGetMenuInfo {
  /**
   *
   * @type {MenuInfoDto}
   * @memberof OrderGetMenuInfo
   */
  menuInfo: MenuInfoDto;
}
