/* tslint:disable */
/* eslint-disable */
/**
 * Mcafe V2 API
 * Mcafe V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { OrderDto } from './order-dto';

/**
 * 주문 생성 응답 객체
 * @export
 * @interface OrderResponseCreate
 */
export interface OrderResponseCreate {
  /**
   *
   * @type {OrderDto}
   * @memberof OrderResponseCreate
   */
  orderDto: OrderDto;
}
