/* tslint:disable */
/* eslint-disable */
/**
 * Mcafe V2 API
 * Mcafe V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 주문 DTO
 * @export
 * @interface OrderDto
 */
export interface OrderDto {
  /**
   *
   * @type {number}
   * @memberof OrderDto
   */
  memberSn: number;
  /**
   *
   * @type {number}
   * @memberof OrderDto
   */
  roomSn: number;
  /**
   *
   * @type {string}
   * @memberof OrderDto
   */
  menuCode: string;
  /**
   *
   * @type {Array<string>}
   * @memberof OrderDto
   */
  optionList: Array<string>;
}
