/* tslint:disable */
/* eslint-disable */
/**
 * Mcafe V2 API
 * Mcafe V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { MemberDto } from './member-dto';
// May contain unused imports in some cases
// @ts-ignore
import { RoomDto } from './room-dto';

/**
 * 방 정보 조회
 * @export
 * @interface RoomResponseGetRoomInfo
 */
export interface RoomResponseGetRoomInfo {
  /**
   *
   * @type {RoomDto}
   * @memberof RoomResponseGetRoomInfo
   */
  room: RoomDto;
  /**
   * 참여자 정보
   * @type {Array<MemberDto>}
   * @memberof RoomResponseGetRoomInfo
   */
  memberList: Array<MemberDto>;
}
