/* tslint:disable */
/* eslint-disable */
/**
 * Mcafe V2 API
 * Mcafe V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 방 생성 정보
 * @export
 * @interface RoomRequestCreate
 */
export interface RoomRequestCreate {
  /**
   *
   * @type {string}
   * @memberof RoomRequestCreate
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof RoomRequestCreate
   */
  status: RoomRequestCreateStatusEnum;
  /**
   *
   * @type {string}
   * @memberof RoomRequestCreate
   */
  password?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum RoomRequestCreateStatusEnum {
  CLOSED = 'CLOSED',
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE',
}
