/* tslint:disable */
/* eslint-disable */
/**
 * Mcafe V2 API
 * Mcafe V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 방 정보 수정 요청 객체
 * @export
 * @interface RoomRequestUpdateRoom
 */
export interface RoomRequestUpdateRoom {
  /**
   *
   * @type {number}
   * @memberof RoomRequestUpdateRoom
   */
  roomSn: number;
  /**
   *
   * @type {string}
   * @memberof RoomRequestUpdateRoom
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof RoomRequestUpdateRoom
   */
  status?: RoomRequestUpdateRoomStatusEnum;
  /**
   *
   * @type {string}
   * @memberof RoomRequestUpdateRoom
   */
  password?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum RoomRequestUpdateRoomStatusEnum {
  CLOSED = 'CLOSED',
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE',
}
