/* tslint:disable */
/* eslint-disable */
/**
 * Mcafe V2 API
 * Mcafe V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 방 입장 요청 객체
 * @export
 * @interface RoomRequestEnterRoom
 */
export interface RoomRequestEnterRoom {
  /**
   *
   * @type {string}
   * @memberof RoomRequestEnterRoom
   */
  password?: string;
}
